- hosts: webserver
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - python3-pip

    - name: Copy application files
      copy:
        src: ../app/
        dest: /var/www/terraform_app/

    - name: Install Python requirements
      pip:
        requirements: /var/www/terraform_app/requirements.txt

    - name: Start application
      command: python3 /var/www/your_app/app.py